### ISSUE TITLE
Can't select Listeners

### ISSUE THREAD

**Issue by Luc45** [Pierre-Lannoy/wp-decalog#11]
**Describe the bug**
Can't choose which Listeners to show

**To Reproduce**
1. Go to wp-admin/options-general.php?page=decalog-settings&tab=listeners
2. Switch from "All available listeners" to "Selected Listeners"
3. Optionally select some listeners. Save.
4. "All available listeners" option will be selected again.

**Expected behavior**
On step 4, it should show "Selected Listeners".

**Environment (please complete the following information):**
 - PHP version: 7.2.5
 - WordPress version and flavour 5.3.1

**Additional context**
I've just installed the plugin, I want to disable all listeners and add just my own listener for custom events in my website.

**Comment by Pierre-Lannoy** [comment]
Hello @Luc45 !
That's really strange as I'm currently not able to reproduce this behavior. Are you using the version available on wp.org or the current dev (on GitHub)?

**Comment by Luc45** [comment]
I'm using the one from WP.org

**Comment by Pierre-Lannoy** [comment]
OK. I'm able to reproduce this issue on fresh WP5.3.1... Let me investigate it....

**Comment by Pierre-Lannoy** [comment]
I found the root cause and just releases the 1.7.2 to fix it.
Could you update your plugin and give me a feedback about it?
Thanks.

**Comment by Luc45** [comment]
Yup, working now, thanks! Nice code, congratulations!

**Comment by Pierre-Lannoy** [comment]
Thanks a lot! And thank you to create this issue...
Don't hesitate to submit a PR if you write a listener for a wp.org plugin ;)
