### ISSUE TITLE
Add sitedomain to event logging

### ISSUE THREAD

**Issue by JanThiel** [Pierre-Lannoy/wp-decalog#16]
**Is your feature request related to a problem? Please describe.**
Currently there is the siteid and the sitename within the meta of an event log entry. The name may not be easily matchable to a single site in a multisite environment. The id again requires an additional lookup step to identify the origin site. Having the domain would allow a direct access to the origin site (<domain>/wp-admin for example). In addition to that the domain is more stable than the name of a site and thus better suited as a readable identifier within tools like Datadog. Currently one would have to know the ID to create stable filters / queries. The domain would be better.

**Describe the solution you'd like**
Add a new field `sitedomain` containing the sites domain.

**Describe alternatives you've considered**
None. Small change, big effect

**Comment by Pierre-Lannoy** [comment]
Hi Jan!
You're definitely right. That's a good thing to have. Let me review your PR....

**Comment by Pierre-Lannoy** [comment]
Many thanks, Jan, for your PR.
It will be in DecaLog 3.2.0...

**Comment by JanThiel** [comment]
Thank you very much @Pierre-Lannoy for this amazing Toolset :-) Glad to contribute.
