### ISSUE TITLE
OPcache logging cannot handle multi-server environments

### ISSUE THREAD

**Issue by JanThiel** [Pierre-Lannoy/wp-decalog#21]
**// UPDATE**
**Describe the bug**
The logging of a manual opcache restart is triggered frequently as the compare is only capable of handling a single server. When there are more servers (cluster setup) the state in the WP site meta only reflects one server. Comparing the states of other running servers leads to false assertions and false logging.

https://github.com/Pierre-Lannoy/wp-decalog/blob/33f890c8e9cd40b8cc50e18e412734a877f404c4/includes/listeners/class-phplistener.php#L252

**Steps to reproduce the behavior:**
1. Run a single WordPress installation with a shared DB on two (or more) servers
2. Trigger a manual `opcache_reset` on one of the servers
3. The log will then be flooded with the false positive message due to the compare of `manual_restarts => 0` (WP Site Meta) with `manual_restarts => 1` (return of `opcache_get_status(false)` ) or the other way around - whenever the server with the other value executes code.

Fix: Store the Opcache status with a server identifier like the hostname

Quickfix: Restart php-fpm to align the status counter

**Comment by JanThiel** [comment]
Our logging says yes:
![image](https://user-images.githubusercontent.com/3857275/137444283-01e27e37-3cc6-4405-ae31-7c692b9f363b.png)

**Comment by Pierre-Lannoy** [comment]
OK, I just have a deep look on your screenshot and forget my last question: availability is ok (so, you have an operational cron ;) ), "cached file" is bad value, you should have something about 4K-6K files on a "standard" WP install with some plugins. And, worst: "hit ratio" is uncomputable. The main reason for that may be that OPcache is reset more frequently than 5 minutes (the frequency of analytics hits)...

**Comment by JanThiel** [comment]
Looks that way :-/ Still no clue what that might be... Anyway, thanks for your support :-)
I will close this issue as this is nothing wrong with Decalog :-)

**Comment by JanThiel** [comment]
Hmm ... strange things. The Opcache Monitor is still empty. Yet I checked the stats that Decalog writes into the site meta. And that actually looks good and fine to me:

```
$ wp network meta get 1 decalog_web_server_php_opcache
array (
  'opcache_enabled' => true,
  'cache_full' => false,
  'restart_pending' => false,
  'restart_in_progress' => false,
  'memory_usage' =>
  array (
    'used_memory' => 188010616,
    'free_memory' => 80424840,
    'wasted_memory' => 0,
    'current_wasted_percentage' => 0.0,
  ),
  'interned_strings_usage' =>
  array (
    'buffer_size' => 12582464,
    'used_memory' => 12582464,
    'free_memory' => 0,
    'number_of_strings' => 178676,
  ),
  'opcache_statistics' =>
  array (
    'num_cached_scripts' => 6498,
    'num_cached_keys' => 9007,
    'max_cached_keys' => 65407,
    'hits' => 45844488,
    'start_time' => 1634283969,
    'last_restart_time' => 0,
    'oom_restarts' => 0,
    'hash_restarts' => 0,
    'manual_restarts' => 0,
    'misses' => 6875,
    'blacklist_misses' => 0,
    'blacklist_miss_ratio' => 0.0,
    'opcache_hit_rate' => 99.98500589829794,
  ),
)
```

In addition to that there are no new Opcache related warnings in the log. It _seems_ kind of solved. Which is weird because all I changed was the mentioned addition of Opcache to the CLI process PHP config.
I also added some debug code to the only plugin possibly calling `opcache_reset` (Yoast SEO btw., it is condition guarded but relies on versions and an option value), but that didn't fire till now.

**Comment by Pierre-Lannoy** [comment]
Hi @JanThiel !
Currently working on this issue and have some questions…
Can I assume the difference between instances (taking part in the cluster) are fully synchronised in term of local fs, php versions, installed modules, etc. (if so, how? - are they k8s nodes?)? If yes, the only "difference" between them is memory, opcode caching and maybe temp fs. Can you confirm this?

Thanks for your help.

**Comment by JanThiel** [comment]
Hi @Pierre-Lannoy Yes, all nodes are synced in terms of software, config and version of the software.
In our scenario all nodes are bare metal. Config Management is done using Ansible.

PHP, OS, Patchlevel and such are all identical on all machines ( if nothing goes wrong ;-) ). Anything else would be insane.

The file system is NOT synced as all Network-FS have massive negative impact on PHP workload performance, as far as I am aware of.  Keeping the FS in sync is job of the deployment processes and tools.

Speaking of: This means that the opcache state _might_ be slightly different on each node. One cannot assume all nodes build up identically and remain in an equal state at all the time. We already saw different values on the nodes when debugging this issue. 
As written in the issue an easy way to trigger such a state is the `opcache_reset()`. Or more generally speaking: All operations executed by software on only one of the nodes.

Hope this helps. If you require any other information, let me know :-)

**Comment by Pierre-Lannoy** [comment]
YES, this helps 👍🏼 
Thanks for this, I will focus my work on "volatile" things (like OPcache) and not on static ones (like versions).

Just a last question: so, in your scenario, all nodes have a different hostname?

**Comment by JanThiel** [comment]
Yup, each machine has a unique hostname.

**Comment by Pierre-Lannoy** [comment]
Haha. Thanks a lot.
I confirm the 3.3.0 version will fix your issue.
