### ISSUE TITLE
Make Metrics to collect configurable

### ISSUE THREAD

**Issue by JanThiel** [Pierre-Lannoy/wp-decalog#27]
**Is your feature request related to a problem? Please describe.**
Metrics are an amazing tool to get insight into an application. But with the major analytics platforms charging by the number of metrics collected, it is a matter of cost to decide which metrics to actually trace. There are several metrics which create an exponential growth in the number of traced metrics.

**Describe the solution you'd like**
Within `admin.php?page=decalog-settings&tab=metrics` allow to enable / disable the single metric. This will allow one to limit the metrics to those really required and thus controlling the created costs by the metrics.

**Describe alternatives you've considered**
Select the metrics to submit within the configured metrics provider. As it might be different for each provider / connection.

**Additional context**
We use Datadog. With the Decalog default enabled and metrics submitted on a Multisite Environment we very quickly had several hundred metrics billed there. We then disabled the metrics collection for cost reason.

**Comment by Pierre-Lannoy** [comment]
Hi @JanThiel !

That's definitely a really good suggestion. And a must-have feature I will implement in the next version.
I'm currently trying some ways to do that, because unfortunately having checkboxes for all metrics is neither practical nor feasible:
- all PerfOps One plugins publish metrics via DecaLog (and by this I mean A LOT of metrics ;))
- as metrics are dynamically published, it would be impossible to have all the list in UI, so impossible to check/uncheck

**Comment by JanThiel** [comment]
Thank you :-)
Groups by source would be a possible way to reduce the amount of required config... But I am sure you will come up with a smart and handy solution as always ;-)

**Comment by Pierre-Lannoy** [comment]
Ahaha. Thanks.
Note for now, the best way I found is to allow regex for including/excluding metrics (on a per-logger basis) 🤣 
(and it's not even a joke )

**Comment by Pierre-Lannoy** [comment]
Hello @JanThiel !
Do you have some news on this? Is it usable from your point of view?
Thanks ;)

**Comment by JanThiel** [comment]
@Pierre-Lannoy So sorry for not getting back to you! :-/ Simply slipped my todo list...
Feature looks good and is very usable 🚀❤️ 

Thank you very much!
