### ISSUE TITLE
Support custom Jaeger tags

### ISSUE THREAD

**Issue by stevapple** [Pierre-Lannoy/wp-decalog#28]
**Is your feature request related to a problem? Please describe.**
The Jaeger endpoint I’m given is shared by multiple users, and it will classify different applications by `token` tag. Currently `wp-decalog` cannot specify custom tags, so I’m not able to use the service.

**Describe the solution you'd like**
Allow users to set custom Jaeger tags.

**Describe alternatives you've considered**
Can’t think of any alternative yet.

**Additional context**
I’ve opened a PR on the Jaeger client library for supporting client-level tag configuration. Before that work is done, we can workaround by setting the tags on each spans.

**Comment by Pierre-Lannoy** [comment]
Hello @stevapple !
I see your [issue](https://github.com/jonahgeorge/jaeger-client-php/issues/121) on the client library. As soon as it is solved, I will implement it in DecaLog.

Thanks for the suggestion.

**Comment by stevapple** [comment]
I checked the source and found that Decalog is not using the Jaeger client directly, but instead constructing a Thrift payload directly?

Then we shouldn’t need such feature. The only solution is to manually append the tags in `Decalog\Handler\ AbstractTracingHandler:jaeger_format`.

**Comment by Pierre-Lannoy** [comment]
Hello @stevapple !
Sorry for this late answer…
If I understand well what you're suggesting, the best way to do what you want to achieve is to allow to set custom tags at the logger creation (as key/value pairs) and propagate it for all spans before sending. Am I right?

**Comment by stevapple** [comment]
I think yes:)

**Comment by Pierre-Lannoy** [comment]
OK, understood.
I will try to do it for 3.6 version of the plugin which will be ready for WP 6.1 release…

**Comment by Pierre-Lannoy** [comment]
Hello!
Version 3.6.0 is released. Could you confirm it fixes your issue?
Thanks 😉

**Comment by Pierre-Lannoy** [comment]
You have to set the corresponding option (it's off by default):
<img width="925" alt="Capture d’écran 2022-10-06 à 11 12 55" src="https://user-images.githubusercontent.com/15095492/194274441-124f86fe-d941-41b5-b57a-6b4024e5242c.png">

**Comment by Pierre-Lannoy** [comment]
You have to specify it in the logger settings:
<img width="925" alt="Capture d’écran 2022-10-06 à 11 15 19" src="https://user-images.githubusercontent.com/15095492/194274990-bdb52d7b-d59e-4b34-9895-13093dc25719.png">

**Comment by stevapple** [comment]
I used Jaeger and its log level is fixed to emergency. Is that why I’m not seeing any traces? Any way to change the behavior?

**Comment by Pierre-Lannoy** [comment]
There's no "log level" in traces. Traces are collections of spans with tags. And, as all tracers I know, Jaegger do not manipulate the "concept" of log level (except for its own debugging).
So, I do not understand… What do you want to achieve?

**Comment by stevapple** [comment]
🤔So… I can see events being processed by Decalog, but there’s no reports on my APM dashboard, so it’s reasonable to assume there’s something wrong in the middle, right?

Then is there anyway to debug?

**Comment by stevapple** [comment]
Wait, must I add custom events through SDK to get spans? Is there built-in spans injected for WordPress and PHP?

**Comment by Pierre-Lannoy** [comment]
Of course there is 😉 but I think it's not currently the issue.
Please, can you confirm what you want to send to your apm: events or traces?

**Comment by Pierre-Lannoy** [comment]
I close this due to inactivity and because, from my side, change is done and working.
