### ISSUE TITLE
Core class: new metric theme updatable 

### ISSUE THREAD

**Issue by deltaecho07** [Pierre-Lannoy/wp-decalog#29]
**Is your feature request related to a problem? Please describe.**
I would like to export a new metric from the core class. At the moment I can export `wordpress_core_wordpress_plugin_updatable` but there is no metric for themes. I've set up a prometheus endpoint and a grafana dashboard. An alert is triggered, when a plugin is updatable. I would like to implement the same process for a theme update.

**Describe the solution you'd like**
I would like to have an additional Core Class metric, something like `wordpress_core_wordpress_theme_updatable`.

**Describe alternatives you've considered**
No alternatives considered at the moment.

**Comment by Pierre-Lannoy** [comment]
Hello @deltaecho07 !
Thanks you so much for this suggestion. It will be implemented in the next version (3.6.0). You will have 2 new metrics:
`wordpress_core_wordpress_theme_installed` and `wordpress_core_wordpress_theme_updatable`.

**Comment by deltaecho07** [comment]
Hey @Pierre-Lannoy 
Thank you for the quick response and your work! I am looking forward to the new release :)

**Comment by Pierre-Lannoy** [comment]
Hello!
Version 3.6.0 is released. Could you confirm it fixes your issue?
Thanks 😉
