### ISSUE TITLE
Console breaks under php 8.x.x env

### ISSUE THREAD

**Issue by stuffeh** [Pierre-Lannoy/wp-decalog#33]
**Describe the bug**
Perfopsone-consoles functionality break under PHP 8.x.x, even though https://wordpress.org/support/topic/php-8-fatal-error-3/ states it should be functional.

**To Reproduce**
1. Run with PHP 8.0 or PHP 8.1
2. Go to ./wp-admin/admin.php?page=perfopsone-consoles
3. Select any of the options available, such as Live API Calls, Live Events, or Vibes Signals.
4. [Endlessly loops listening for API connection](https://i.imgur.com/FdQHn2y.png)

**Expected behavior**
It [connects to the API](https://i.imgur.com/UGAM7gJ.png). 

**Screenshots**
Broken: https://i.imgur.com/FdQHn2y.png
Expecting: https://i.imgur.com/UGAM7gJ.png

**Environments:**
Test server:
 - nginx 1.22.0
 - PHP version: PHP 8.0.x and 8.1.x. Got it to work on PHP 7.4.32.
 - WordPress 6.0.2
 - Other info: Nothing

Production server:
 - nginx 1.22.0
 - PHP version 8.1.x
 - Wordpress 5.9.4
 - Too many plugins...

**Additional context**
Was mislead about the plugin's status since https://wordpress.org/support/topic/php-8-fatal-error-3/ stated it should be working on PHP 8.

**Comment by stuffeh** [comment]
While I'm here. Do you have any idea if PerfOps One suit logs the traffic that hits fastcgi cache? Gut instinct says no, but figured I'd check with you. Any chance of a nginx flavored reports plugin?

**Comment by Pierre-Lannoy** [comment]
Hello @stuffeh !

Thanks for this report. I was able to reproduce it, not on all my tests but sufficiently to see it. I will fix it for the 3.6 release…

Regarding the traffic logging  and caching tools and strategies, could you just open an issue or (better) a [discussion](https://github.com/Pierre-Lannoy/wp-decalog/discussions)? In short: it depends of what you mean by "traffic"…

**Comment by Pierre-Lannoy** [comment]
I confirm 3.6 release of DecaLog will contain a fix for this. Release is planned in 3 weeks max…

**Comment by stuffeh** [comment]
Yep, it works now. Thank you.
