### ISSUE TITLE
[Performance] Optimize / Reduce (expensive) log events

### ISSUE THREAD

**Issue by JanThiel** [Pierre-Lannoy/wp-decalog#37]
**Is your feature request related to a problem? Please describe.**
We currently profile our WP setup. Decalog popped up as a source of too much rendering-time on nearly all requests.

See the profiling chart on the right in light and dark green. In this request the `CoreListener::plugin_close` causes about **40%** of the rendering time of that page. All Decalog is at about 52% of this single request. The remaining time comes from `DatabaseListener::db_monitoring_close`.

![image](https://user-images.githubusercontent.com/3857275/195803993-7eb596e1-d7a9-446a-8fda-34cc7a23fa38.png)

The source is within the `CoreListener::plugin_close` with its calls to `plugin_update` and `theme_update` causing HTTP requests to the external repos. As we all know that HTTP requests are ~bad and evil~ slow these operations should be used rarely and never in frontend or AJAX requests. `DatabaseListener::db_monitoring_close` does uncached SQL queries. Even something I would like to skip performancewise ;-).

**Describe the solution you'd like**
There are two solutions coming into my mind:

1. General approach: We do not have any metrics provider configured by choice in this environment. So why are metrics even collected? The `plugin_close` method as well as `db_monitoring_close` only work on counters which are only relevant if a metric provider is configured, correct? 
Could we add a layer of "check what to collect before collecting it"? Like `collect_metrics():true|false` and `collect_events():true|false` and add them around the proper functions before executing and hooking stuff? Should reduce the footprint of the plugin to the only required level.

3. For this particular case: Limit the execution of the plugin functions to authenticated admin calls with the capabilities to actually update plugins.

**Additional context**
WPMU 6.0.2
PHP 7.4.<latest>

**Comment by JanThiel** [comment]
Just to add for sure regarding the plugin & theme update: This only happens if the transients are not filled. So it's not a general issue. But it happens from time to time.

**Comment by JanThiel** [comment]
👍 Sounds perfect to me. And please don't call it "bad assumption" it's just that other people have other usecases ;-) So i'ts merely an evolution. And that's what OpenSource is all about, isn't it? Contributing and developing stuff together.

And yea, there was as well something off with these transients on our setup in some edge cases 👼. Fixed that already. But that was still nice to uncover these things in Profiling.

Just for some background info and experience from our past: We once tested and used [WSAL ](https://de.wordpress.org/plugins/wp-security-audit-log/) from Robert and White Hat Sec for some time. It kind of does the same as Decalog but focussed on Audit logging ;-). They as well triggered several performance issues back then due to the way WordPress is built and some events are constructed. All these things don't matter in "small" setups. But whenever something scales, like media files or entries, these logging event do have a relevant impact. In particular we had the issue with WP Menus. As each item save triggers a log event it tends to create timeouts with very very very huge menus with lots of menu items. Thus rendering the menus impossible to save.
I just wanted to share that to avoid these pitfalls with Decalog :-)

Have a great weekend!

**Comment by Pierre-Lannoy** [comment]
> And please don't call it "bad assumption" it's just that other people have other usecases ;-) So i'ts merely an evolution. And that's what OpenSource is all about, isn't it? Contributing and developing stuff together.

Definitely in deep agreement with this ❤️ 

Regarding your experience with WSAL, I see what you have in mind. Nevertheless, I do not blame them. They made a choice of something simple (simplistic?) that match with mainstream needs. That's not the case with DecaLog: I've made the choice of something efficient, powerful and "deeper" (so, more technical, unfortunately). And I want to do everything to be as efficient as possible. Your remarks and suggestions on this matter are unvaluable for me… So thanks again!

**Comment by JanThiel** [comment]
@Pierre-Lannoy Just feeding you ideas and wishes :-)

Thank you very much for providing such an extensive and amazing support and ongoing development.

**Comment by Pierre-Lannoy** [comment]
Version 3.7.0 released. This feature is implemented.
Many thanks for the suggestion 😉
