### ISSUE TITLE
CLI commands 'wp log listener enable/disable' work incorrectly

### ISSUE THREAD

**Issue by AlexMazey** [Pierre-Lannoy/wp-decalog#38]
**Describe the bug**
When I try to run a CLI command 'wp log listener disable wpdb' it returns a message 'Invalid listener id supplied' and exit. 
The 'wpdb' listener definitely exists, as it is a standard one and it is shown in the listeners list after running 'wp log listener list'.

The root cause is in the line 1146 of includes/features/class-wpcli.php
https://github.com/Pierre-Lannoy/wp-decalog/blob/master/includes/features/class-wpcli.php
Looks like the $listeners array is always empty in that condition, so the $uuid becomes empty for each command with arguments.

**To Reproduce**
1. Open any tool to run a WP CLI.
2. Run the command: wp log listener disable wpdb
3. See the error message

**Expected behavior**
Disabling the specified listener, in case of disable command. 
Enabling the specified listener, in case of enable command.

**Environment (please complete the following information):**
 - PHP version: 7.4.30
 - WordPress version: WordPress MU 6.0.2
 - Decalog version: 3.5.1

**Comment by Pierre-Lannoy** [comment]
OMG 😱 
I confirm the bug. Let me see what's going on…

**Comment by Pierre-Lannoy** [comment]
New 3.6.2 version released. Can you confirm it fixes the issue?
Thanks

**Comment by AlexMazey** [comment]
Hello Pierre,

I have just tested the latest version and I confirm that the issue is fixed.
Thank you for the quick response!
