### ISSUE TITLE
Jaeger service name support

### ISSUE THREAD

**Issue by stevapple** [Pierre-Lannoy/wp-decalog#48]
**Is your feature request related to a problem? Please describe.**
Currently DecaLog defaults to use the name "WP" as service name in Jaeger. Sometimes we may want to customize the name (since it’s displayed on the tracing dashboard) or avoid collision between multiple WordPress instances.

**Describe the solution you'd like**
Add a new "service name" setting for Jaeger tracers.

**Comment by Pierre-Lannoy** [comment]
Hello @stevapple !
This is a really good suggestion. It is implemented in 3.7.0 (release scheduled in some hours).

Thanks for the suggestion 😉

**Comment by Pierre-Lannoy** [comment]
Version 3.7.0 released. This feature is implemented.
