### ISSUE TITLE
decalog.io broken

### ISSUE THREAD

**Issue by JanThiel** [Pierre-Lannoy/wp-decalog#54]
Hey @Pierre-Lannoy,

just FYI: https://decalog.io/ seems to be broken. All links lead to the main page only.

Have a great weekend!

Jan

**Comment by Pierre-Lannoy** [comment]
Hello @JanThiel !
Thanks for the hint. And sorry for the inconvenience.
I was planning to migrate PerfOps One and decalog.io websites to my new hosting company (Hosterra) this summer. Seems I will have to anticipate it…

**Comment by Pierre-Lannoy** [comment]
Hello @JanThiel ! 
[PerfOps One](https://perfops.one) and [DecaLog SDK](https://decalog.io) websites have been migrated on [Hosterra](https://hosterra.eu/). It must be more stable, now ;)
