### ISSUE TITLE
Incompatibility of Decalog with version 8 elastic

### ISSUE THREAD

**Issue by mahdisarani** [Pierre-Lannoy/wp-decalog#60]
Failure to send logs to Elastic 8

Deprecated: Creation of dynamic property DLGuzzleHttp\Ring\Client\CurlMultiHandler::$_mh is deprecated in /var/www/html/wp-content/plugins/decalog/includes/libraries/guzzlehttp/Ring/Client/CurlMultiHandler.php on line 47

Deprecated: Creation of dynamic property DLGuzzleHttp\Ring\Client\CurlMultiHandler::$_mh is deprecated in /var/www/html/wp-content/plugins/decalog/includes/libraries/guzzlehttp/Ring/Client/CurlMultiHandler.php on line 47

Deprecated: Creation of dynamic property DLGuzzleHttp\Ring\Client\CurlMultiHandler::$_mh is deprecated in /var/www/html/wp-content/plugins/decalog/includes/libraries/guzzlehttp/Ring/Client/CurlMultiHandler.php on line 47

Deprecated: Creation of dynamic property DLGuzzleHttp\Ring\Client\CurlMultiHandler::$_mh is deprecated in /var/www/html/wp-content/plugins/decalog/includes/libraries/guzzlehttp/Ring/Client/CurlMultiHandler.php on line 47

Deprecated: Creation of dynamic property DLGuzzleHttp\Ring\Client\CurlMultiHandler::$_mh is deprecated in /var/www/html/wp-content/plugins/decalog/includes/libraries/guzzlehttp/Ring/Client/CurlMultiHandler.php on line 47

Fatal error: Uncaught Error: Call to a member function error() on null in /var/www/html/wp-content/plugins/decalog/includes/listeners/class-phplistener.php:350 Stack trace: #0 [internal function]: Decalog\Listener\PhpListener->handle_exception() #1 {main} thrown in /var/www/html/wp-content/plugins/decalog/includes/listeners/class-phplistener.php on line 350

Fatal error: Uncaught Error: Call to a member function log() on null in /var/www/html/wp-content/plugins/decalog/includes/listeners/class-phplistener.php:327 Stack trace: #0 [internal function]: Decalog\Listener\PhpListener->handle_error() #1 /var/www/html/wp-includes/functions.php(6031): trigger_error() #2 /var/www/html/wp-includes/functions.php(5975): wp_trigger_error() #3 /var/www/html/wp-includes/query.php(882): _doing_it_wrong() #4 /var/www/html/wp-includes/robots-template.php(93): is_embed() #5 /var/www/html/wp-includes/class-wp-hook.php(324): wp_robots_noindex_embeds() #6 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #7 /var/www/html/wp-includes/robots-template.php(32): apply_filters() #8 /var/www/html/wp-includes/functions.php(3841): wp_robots() #9 /var/www/html/wp-content/plugins/decalog/includes/listeners/class-corelistener.php(1253): _default_wp_die_handler() #10 /var/www/html/wp-includes/functions.php(3763): Decalog\Listener\CoreListener->Decalog\Listener\{closure}() #11 /var/www/html/wp-includes/class-wp-fatal-error-handler.php(239): wp_die() #12 /var/www/html/wp-includes/class-wp-fatal-error-handler.php(154): WP_Fatal_Error_Handler->display_default_error_template() #13 /var/www/html/wp-includes/class-wp-fatal-error-handler.php(58): WP_Fatal_Error_Handler->display_error_template() #14 [internal function]: WP_Fatal_Error_Handler->handle() #15 {main} thrown in /var/www/html/wp-content/plugins/decalog/includes/listeners/class-phplistener.php on line 327

I use version 8.2 of PHP.
From WordPress version 6.4.3
From the last edition of the Decalog
But the above error exists for.

Thank you for your guidance.

**Comment by Pierre-Lannoy** [comment]
Hello @mahdisarani !

Thanks for the report. It is due to a deprecated / abandoned library for GuzzleHttp. I will try to fix it for the next release.
